require:
  - rubocop-performance
inherit_from:
  - ./departments/layout.yml
  - ./departments/lint.yml
  - ./departments/metrics.yml
  - ./departments/performance.yml
  - ./departments/rspec.yml
  - ./departments/style.yml
